"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w9AZEZq
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useState } from "react";

export function Hero() {
  const [pdf, setPdf] = useState<File | null>(null);
  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData();
    if (!pdf) {
      console.log("No pdf found!");
      return;
    }
    formData.append("pdf", pdf);
    const response = await fetch("/api/upload", {
      method: "POST",
      body: formData,
    });
    if (response.ok) {
      console.log("Success");
    } else {
      console.log("Failed");
    }
  };
  return (
    <section className="w-full h-screen py-12 md:py-24 lg:py-32 xl:py-48 bg-black">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 items-center">
          <div className="flex flex-col justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-500">
                Chat with your PDFs
              </h1>
              <p className="max-w-[600px] text-zinc-200 md:text-xl dark:text-zinc-100 mx-auto">
                Upload your PDFs and chat with it, No need to read full pdf.
              </p>
            </div>
            <div className="w-full max-w-sm space-y-2 mx-auto">
              <form className="flex space-x-2" onSubmit={onSubmit}>
                <Input
                  className="max-w-lg flex-1"
                  type="file"
                  onChange={(e: any) =>
                    setPdf(e.currentTarget.files?.item(0) as File)
                  }
                />
                <Button className="bg-white text-black" type="submit">
                  Upload
                </Button>
              </form>
              <p className="text-xs text-zinc-200 dark:text-zinc-100">
                All chats will be stored.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
