"use client";

import Uploader from "../uploader";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w9AZEZq
 */

export function Hero() {
  return (
    <section className="w-full h-screen py-12 md:py-24 lg:py-32 xl:py-48 bg-black">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 items-center">
          <div className="flex flex-col justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-500">
                Chat with your PDFs
              </h1>
              <p className="max-w-[600px] text-zinc-200 md:text-xl dark:text-zinc-100 mx-auto">
                Upload your PDFs and chat with it, No need to read full pdf.
              </p>
            </div>
            <div className="w-full max-w-sm space-y-2 mx-auto">
              <Uploader />
              <p className="text-xs text-zinc-200 dark:text-zinc-100">
                All chats will be stored.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
